require 'rake/clean'

CLOBBER.include('*.html', 'screen.css')

task :default => ['index.html', 'screen.css']

rule '.html' => '.haml' do |t|
  sh "haml -f html5 #{t.source} > #{t.name}"
end

rule '.css' => '.sass' do |t|
  sh "sass #{t.source} > css/#{t.name}"
end

desc 'View the web page in Google Chrome.'
task :view => 'index.html' do 
  sh "google-chrome index.html"
end
